const questions = [
 {
  "difficulty": "medium",
  "points": 2,
  "text": "Üstü tamamen kapalı bir stadyumda oynanan ilk FIFA Dünya Kupası maçı hangi yıl gerçekleşmiştir?",
  "choices": ["1990", "1994", "1998", "2002"],
  "answer": 1,
  "hint": "Bu turnuva, Kuzey Amerika'da düzenlenen ilk Dünya Kupası'ydı.",
  "fact": "Pontiac Silverdome'un çimi, doğal güneş ışığından yoksun kapalı yapı nedeniyle özel tasarlanmış yapay aydınlatma sistemiyle büyütüldü — Dünya Kupası tarihinde bir ilk. Stadyum 2017'de yıkıldı.",
  "image": null,
  "fact_image": "https://static01.nyt.com/athletic/uploads/wp/2024/08/21042228/GettyImages-232502-e1724228575147.jpg?width=1200&height=1200&fit=cover",
  "tags": ["1994", "ABD", "Pontiac Silverdome", "tarih", "kapalı stadyum"]
},
  {
  "difficulty": "hard",
  "points": 3,
  "text": "1994 Dünya Kupası'nda Pontiac Silverdome'da oynanan ve kapalı stadyumdaki ilk Dünya Kupası maçı unvanını alan karşılaşmada hangi iki ülke sahaya çıktı?",
  "choices": ["ABD - İsviçre", "ABD - Kolombiya", "ABD - Romanya", "ABD - Meksika"],
  "answer": 0,
  "hint": "Ev sahibi ülke, bu maçı 1954 Dünya Kupası'na ev sahipliği yapan Avrupa ülkesine karşı oynadı.",
  "fact": "Silverdome'daki kapalı havanın elektrostatik etkisinden futbolcular şikâyetçi oldu — FIFA'nın ilk ve son kapalı stadyum denemesi oldu. Wynalda'nın golü, çoğunun hafızasında kaldı.",
  "image": null,
   "tags": ["1994", "ABD", "İsviçre", "Pontiac Silverdome", "grup aşaması", "Eric Wynalda"]
},
 {
  "difficulty": "medium",
  "points": 2,
  "text": "1982 Dünya Kupası'nda Sócrates liderliğindeki Brezilya'yı ikinci turda eleyerek turnuvayı kazanan takım hangisiydi?",
  "choices": ["Fransa", "Arjantin", "İtalya", "Batı Almanya"],
  "answer": 2,
  "hint": "O maçta karşı takımın golcüsü, turnuvanın gol krallığını da kazandı — iki yıl önce şike skandalıyla sahalardan uzaklaştırılmıştı.",
  "fact": "İtalya-Brezilya (3-2), Dünya Kupası tarihinin en çok atıfta bulunulan maçlarından biridir. Paolo Rossi, iki yıllık men cezasının ardından döndüğü ilk büyük turnuvada hat-trick yaptı. Sócrates, Zico ve Falcão'nun o kadrosu galip gelseydi tarih farklı yazılırdı — bazı analistlere göre 1982 Brezilya'sı, hiç kazanamamış en iyi Dünya Kupası takımıdır.",
  "image": null,
  "tags": ["1982", "Brezilya", "Sócrates", "İtalya", "Paolo Rossi", "ikinci tur"]
},
 {
  "difficulty": "medium",
  "points": 2,
  "text": "1982 ve 1986 Dünya Kupalarında Brezilya'nın ikonik ismi Sócrates, sahalar dışında da sıra dışı bir yaşam sürdü. 'O Doutor' lakabının kaynağı neydi?",
  "choices": [
    "Felsefi yazılar kaleme alması",
    "Aktif kariyerinde tıp fakültesinden mezun olması",
    "Corinthians'ta demokratik yönetim modeli kurması",
    "Sahada oyun kuruculuğunu doktor titizliğiyle icra etmesi"
  ],
  "answer": 1,
  "hint": "Bu unvan metafor değil — gerçek bir akademik derecenin ürünü.",
  "fact": "Sócrates, 1984'te Ribeirão Preto Tıp Fakültesi'nden mezun oldu; hâlâ aktif bir profesyonel futbolcuyken. Aynı dönemde kurduğu Corinthians Demokrasisi'nde kulüp kararları oyuncuları, teknik ekibi ve temizlik personelini kapsayan eşit oylamayla alınırdı. Sahada kaybetti, ama yarattığı modeller kaldı.",
  "image": null,
  "tags": ["Sócrates", "Brezilya", "O Doutor", "1982", "1986", "Corinthians"]
},
 {
  "difficulty": "hard",
  "points": 3,
  "text": "FIFA'nın 2002'de düzenlediği oylamayla 'Yüzyılın Golü' seçilen Maradona'nın o vuruşunda kaç İngiliz oyuncu geçildi?",
  "choices": ["4", "5", "6", "7"],
  "answer": 1,
  "hint": "Sayım yöntemine göre tartışmalıdır — ama FIFA'nın resmi sayısı hem kaleci hem saha oyuncularını kapsar.",
  "fact": "Maradona kendi yarı sahasında topla buluştu, Reid, Beardsley, Butcher, Fenwick ve kaleci Shilton'ı geçerek gol attı — toplam 11 saniyede 60 metre. Butcher ile iki kez karşılaşıldığı için 'geçilen oyuncu sayısı' 5 mi 6 mı tartışması hâlâ sürer. 2002 oylamasında Maradona'nın golü, Puskas'ın, Pelé'nin ve Zidane'ın gollerini geride bıraktı.",
  "image": null,
  "tags": ["1986", "Maradona", "Yüzyılın Golü", "İngiltere", "Arjantin", "Azteca", "çeyrek final"]
},
 {
  "difficulty": "medium",
  "points": 2,
  "text": "22 Haziran 1986'da Azteca Stadı'nda oynanan Arjantin-İngiltere çeyrek finalinde 'Tanrı'nın Eli' golünde topu çıkaramayan İngiliz kaleci kimdi?",
  "choices": ["Gordon Banks", "Ray Clemence", "Peter Shilton", "Chris Woods"],
  "answer": 2,
  "hint": "Bu kaleci, 1970 Dünya Kupası'nda Pelé'nin golünü kurtarmasıyla da tarihe geçmişti.",
  "fact": "Peter Shilton, maçın ardından yıllarca Maradona'yı affetmediğini açıkça dile getirdi. Maradona ise 2005'te verdiği bir röportajda 'Tanrı'nın Eli'nin esasen İngilizlere ve İngiltere'ye bir yanıt olduğunu' ima etti — 1982 Falkland Savaşı'nın gölgesi o maça kadar uzanıyordu.",
  "image": null,
  "tags": ["1986", "Maradona", "Tanrı'nın Eli", "İngiltere", "Arjantin", "Peter Shilton", "çeyrek final"]
},
 {
  "difficulty": "medium",
  "points": 2,
  "text": "22 Haziran 1986'da Arjantin-İngiltere çeyrek finaline ev sahipliği yapan Azteca Stadı'nda o gün tribünleri kaç kişi doldurdu?",
  "choices": ["98.540", "107.160", "114.580", "122.300"],
  "answer": 2,
  "hint": "O gün stadyumda bulunan taraftar sayısı, bugün Azteca'nın resmi kapasitesinin çok üzerindeydi.",
  "fact": "2026 Dünya Kupası için renovasyondan geçen Azteca'nın güncel kapasitesi 87.523'e indirildi. Maradona'nın o gollerine tanıklık eden 114.580 kişilik kalabalık ise 2026'da ilk kez Dünya Kupası'na katılan Curaçao'nun toplam nüfusunun (yaklaşık 153.000) yüzde yetmişbeşini oluşturuyordu — yani o gün Azteca'daki izleyicilerin dörtte üçü kadar bir ada, bu yıl futbol dünya sahnesine çıkıyor.",
  "image": null,
  "tags": ["Azteca", "1986", "kapasite", "Arjantin", "İngiltere", "Curaçao", "2026"]
},
 {
  "difficulty": "medium",
  "points": 2,
  "text": "1970'lerin başında iki yıl içinde Şampiyon Kulüpler Kupası'nda Inter'i ve Juventus'u eleyip Süper Kupa'da da Milan'ı 6-0 mağlup eden; bu üç İtalyan devine karşı 9 gol atıp hiç gol yemeyen takım hangisiydi?",
  "choices": ["Bayern Münih", "Ajax", "Feyenoord", "Borussia Mönchengladbach"],
  "answer": 1,
  "hint": "Bu takım, Johan Cruyff liderliğinde Total Futbol'u Avrupa'ya dayattı — ve üst üste üç Avrupa şampiyonluğu kazandı.",
  "fact": "1971-73 arasında Ajax, Avrupa Kupası'nı üst üste üç kez kazandı. Bu dönemde Rinus Michels ve Johan Cruyff'un şekillendirdiği Total Futbol, pozisyon kavramını yeniden tanımladı. Calcio'nun kalesi sayılan üç İtalyan devi bu süreçte hiç gol atamadan sahadan çekildi.",
  "image": null,
  "tags": ["Ajax", "Total Futbol", "1970ler", "Avrupa Kupası", "Cruyff", "Inter", "Juventus", "Milan"]
},
 {
  "difficulty": "easy",
  "points": 1,
  "text": "FIFA Dünya Kupası tarihinde en fazla gol atılan organizasyon hangisidir?",
  "choices": ["2014 Brezilya", "1998 Fransa", "2022 Katar", "2006 Almanya"],
  "answer": 2,
  "hint": "Bu turnuva, kasım-aralık aylarında oynanan ilk Dünya Kupası'ydı.",
  "fact": "Katar 2022'de 64 maçta 172 gol kaydedildi; böylece 171 golle ikinci sıraya düşen 2014 Brezilya'yı geçti. Sezon ortası turnuva temposunun gol sayısını düşüreceği öngörülmüştü — tam tersi oldu.",
  "image": null,
  "tags": ["2022", "Katar", "rekor", "gol", "istatistik"]
},
 {
  "difficulty": "medium",
  "points": 2,
  "text": "2022 Dünya Kupası'nda İran Milli Takımı oyuncuları, Mahsa Amini protestolarına destek olarak ulusal marşı okumayı reddetti. Bu sessiz duruş hangi maç öncesinde gerçekleşti?",
  "choices": ["Galler", "ABD", "İngiltere", "Senegal"],
  "answer": 2,
  "hint": "İran'ın grup aşamasındaki ilk maçıydı.",
  "fact": "21 Kasım 2022'de İran oyuncuları marş okunurken sessiz kaldı; tribünlerden yükselen 'Jin, Jiyan, Azadî' (Kadın, Yaşam, Özgürlük) sloganları tüm dünyaya canlı yayınlandı. Maçı 6-2 kaybeden İran'ın oyuncuları, ülkelerine döndüklerinde baskıyla karşılaşacakları bilinmesine rağmen bu duruşu sergiledi — bu da protestoyu, Dünya Kupası tarihinin en yüksek bedelli siyasi eylemlerinden biri yaptı.",
  "image": null,
  "tags": ["2022", "Katar", "İran", "İngiltere", "Mahsa Amini", "Jin Jiyan Azadi", "protest"]
},
 {
  "difficulty": "easy",
  "points": 1,
  "text": "2022 Katar Dünya Kupası, turnuva tarihinde en fazla seri penaltıya sahne olan organizasyon oldu. Kaç maçın kazananı seri penaltılarla belirlendi?",
  "choices": ["3", "4", "5", "6"],
  "answer": 2,
  "hint": "Final dahil — Arjantin ile Fransa da kupanın kaderine bu şekilde ortak oldu.",
  "fact": "Katar'dan önce yalnızca iki Dünya Kupası finali seri penaltıyla sonuçlanmıştı: 1994'te Brezilya-İtalya ve 2006'da İtalya-Fransa. 2022 finali bu listeye üçüncü olarak eklendi. Beş maçlık seri penaltı rekoru, turnuvanın 172 gollük gol rekoruyla birleşince Katar 2022'yi hem en gollü hem de en gergin Dünya Kupası yaptı.",
  "image": null,
  "tags": ["2022", "Katar", "penaltı", "rekor", "final", "Arjantin", "Fransa", "istatistik"]
},
  {
  "difficulty": "easy",
  "points": 1,
  "text": "İtalya, 1958'den sonra ilk kez hangi yıl FIFA Dünya Kupası'na katılamadı?",
  "choices": ["2014", "2018", "2022", "2026"],
  "answer": 1,
  "hint": "O eleme maçı San Siro'da, İsveç karşısında oynadıkları play-off'ta geldi.",
  "fact": "İtalya'nın 1958'deki gıyabı, dönemin en büyük şoku sayılırdı. 60 yıl sonra tarihi tekerrür etti — üstelik üç kez arka arkaya. 2018, 2022 ve 2026'yı kapsayan bu seri, Dünya Kupası tarihinin en uzun 'büyük ülke yokluğu' serilerinden biri oldu.",
  "image": null,
  "tags": ["İtalya", "2018", "eleme", "İsveç", "tarih", "1958"]
},
 {
  "difficulty": "medium",
  "points": 2,
  "text": "İtalya'yı 2018, 2022 ve 2026 Dünya Kupası elemelerinde dışarıda bırakan üç ülke arasında hangisi YER ALMAZ?",
  "choices": ["İsveç", "Kuzey Makedonya", "Portekiz", "Bosna Hersek"],
  "answer": 2,
  "hint": "Elemeyen ülke, İtalya'nın güçlü bir rakip olarak her zaman saydığı bir Avrupa devi.",
  "fact": "İsveç (2018), Kuzey Makedonya (2022) ve Bosna Hersek (2026) — İtalya'yı üç sırayla Dünya Kupası dışında bırakan bu üçlünün ortak özelliği: hiçbiri İtalya'nın 'tehlikeli rakip' listesinin ilk sıralarında yer almıyordu. Portekiz ise aynı dönemde her seferinde kendi play-off maçlarını kazandı.",
  "image": null,
  "tags": ["İtalya", "eleme", "2018", "2022", "2026", "İsveç", "Kuzey Makedonya", "Bosna Hersek"]
},
   {
  "difficulty": "easy",
  "points": 1,
  "text": "Avrupa futbolunda serbest transferin önünü açan ve kulüplerin yabancı oyuncu kullanımını kökten değiştiren 'Bosman Kuralları' hangi yıl yürürlüğe girdi?",
  "choices": ["1990", "1992", "1995", "1998"],
  "answer": 2,
  "hint": "Bu kararın mimarı, Belçikalı bir futbolcunun açtığı davayı Avrupa Adalet Divanı'na taşımasıyla geldi.",
  "fact": "Jean-Marc Bosman, sözleşmesi biten bir oyuncunun başka kulübe serbestçe geçememesini Avrupa hukukunda iş özgürlüğü ihlali olarak dava etti ve kazandı. Karar, Serie A başta olmak üzere büyük liglerdeki yabancı oyuncu akışını patlatır gibi artırdı. Bosman'ın kendisi ise bu tarihi zaferin ardından parasız ve unutulmuş bir kariyer sonu yaşadı.",
  "image": null,
  "tags": ["Bosman", "1995", "transfer", "Avrupa hukuku", "serbest transfer", "Serie A"]
},
  {
    "difficulty": "medium",
    "points": 2,
    "text": "\"Eğer 10 yıl önce genç takımlarda böyle bir yeteneğe sahip olacak kadar şanslı olsaydık, onu elimizden kaçırırdık\" sözleriyle İtalyan altyapı sistemini eleştiren teknik direktör ve bahsettiği genç yetenek hangi ikiliydi?",
    "choices": [
      "Arrigo Sacchi – Olise",
      "Cesare Prandelli – Lamine Yamal",
      "Roberto Mancini – Olise",
      "Fabio Capello – Lamine Yamal"
    ],
    "answer": 1,
    "hint": "Bu teknik adamın kariyerinde Galatasaray dönemi de yer aldı.",
    "fact": "İtalya'yı Euro 2012'de finale taşıyan ve 2014'te kısa süre Galatasaray'ı çalıştıran Cesare Prandelli, Lamine Yamal'ın Euro 2024'teki dominasyonu sonrası bu itirafta bulunmuştur. İtalyan futbolunun katı, fiziksel ve kalıplara dayalı altyapı sisteminin, Yamal gibi yaratıcı ve sokak futbolu genetiğine sahip bir deha üretmek bir yana, var olanı da öğüteceğini savunmuştur.",
    "image": null,
    "tags": ["Prandelli", "Yamal", "İtalya", "altyapı", "Galatasaray", "teknik direktör"]
  },
  {
  "difficulty": "medium",
  "points": 2,
  "text": "2026 Dünya Kupası'na ev sahipliği yapacak ABD'de en kalabalık göçmen topluluğunu oluşturan ülke Meksika. Turnuvanın eş ev sahiplerinden olan Meksika kökenli göçmen nüfusu yaklaşık kaçtır?",
  "choices": ["5 milyon", "8 milyon", "11 milyon", "15 milyon"],
  "answer": 2,
  "hint": "Bu nüfus, tek başına birçok Avrupa ülkesinin toplam nüfusunu geride bırakır.",
  "fact": "11 milyonu aşkın Meksika doğumlu göçmen, ABD'nin en büyük tek kökenli yabancı doğumlu grubunu oluşturuyor. 2026'da iki ülke aynı turnuvada hem rakip hem ev sahibi olacak — tribünlerdeki demografik denge, sahadan az ilginç olmayacak.",
  "image": null,
  "tags": ["2026", "ABD", "Meksika", "göçmen", "demografik", "ev sahipliği"]
},
   {
  "difficulty": "easy",
  "points": 1,
  "text": "Futbolu 19. yüzyılın başlarında Meksika'ya taşıyan ve Real del Monte şehrinde ilk kulüpleri kuran Cornwall çıkışlı İngiliz göçmenlerin asıl mesleği neydi?",
  "choices": ["Madenci", "Tekstil İşçisi", "Demiryolu Mühendisi", "Denizci"],
  "answer": 0,
  "hint": "Bu göçmenler, 1825 yılında Meksika'daki gümüş yataklarını yeniden canlandırmak amacıyla bölgeye getirilmişti.",
  "fact": "Cornwall'dan gelen Cornish (Kernevek) madenciler, 1825'te Meksika'daki gümüş madenlerini işletmek için işe alındı. Bölgeye sadece madencilik tekniklerini değil, molalarda oynadıkları futbolu da taşıdılar. Bu göç sayesinde Real del Monte şehri bugün Meksika futbolunun beşiği kabul edilir.",
  "image": null,
  "tags": ["Meksika", "İngiltere", "Cornwall", "Real del Monte", "futbol tarihi", "madencilik"]
},
   {
  "difficulty": "medium",
  "points": 2,
  "text": "Real del Monte'ye ulaşmayı başaran Cornwall'lı madenciler, maç sonrası bir gelenek oluşturdu. Bu gelenek neydi?",
  "choices": [
    "Kazanan takım ertesi sabah madende çalışmaz, dinlenirdi",
    "En şık kıyafetlerini giyip çay partisi düzenlerlerdi",
    "Meksikalı işçilerle ortak bir akşam yemeği yerlerdi",
    "Her maç galibine bir gümüş madalya verilirdi"
  ],
  "answer": 1,
  "hint": "Bu gelenek, İngiliz kültürünün Meksika topraklarına taşınan en tanıdık ritüellerinden biriydi.",
  "fact": "Futbol maçlarının ardından düzenlenen çay partileri, zamanla İngiliz ve Meksikalı işçilerin ortak kültürünün bir parçası haline geldi. Real del Monte, İngiltere dışında futbol oynandığına dair bilinen en eski yerlerden biri — ve bu mirası bir çay geleneğiyle taçlandırdı.",
  "image": null,
  "tags": ["Real del Monte", "Cornwall", "Meksika", "çay", "futbol tarihi", "gelenek"]
},
   {
  "difficulty": "hard",
  "points": 3,
  "text": "Meksika, ev sahibi olduğu FIFA Dünya Kupası sayısıyla tarihte kaç ülkeyle birlikte en fazla turnuvaya ev sahipliği yapan ülkeler arasında yer alır?",
  "choices": [
    "Yalnızca Meksika — 3 turnuvayla tek başına rekordadır",
    "Brezilya ile birlikte — ikisi de 3'er kez ev sahipliği yaptı",
    "İtalya ile birlikte — ikisi de 2'şer kez ev sahipliği yaptı",
    "Fransa, Almanya ve İtalya ile birlikte — hepsi 2'şer kez ev sahipliği yaptı"
  ],
  "answer": 0,
  "hint": "2026 sayılırsa Meksika bu listedeki yerini kimseyle paylaşmaz.",
  "fact": "Meksika 1970, 1986 ve 2026 Dünya Kupalarına ev sahipliği yaparak bu ayrıcalığı üç kez yaşayan tek ülke konumuna geçti. 1986'da ev sahipliği planlanmamıştı — Kolombiya'nın çekilmesiyle Meksika 9 ay içinde organizasyonu devraldı. Futbol tarihindeki en ikonik anlar bu topraklarda yaşandı; kazanmak yerine sahip olmak Meksika'nın asıl uzmanlık alanı oldu.",
  "image": null,
  "tags": ["Meksika", "ev sahipliği", "1970", "1986", "2026", "rekor", "Dünya Kupası tarihi"]
},
    {
  "difficulty": "easy",
  "points": 1,
  "text": "1970 Dünya Kupası, FIFA tarihinde bir ilki daha beraberinde getirdi: maçlar ilk kez hangi teknolojiyle yayınlandı?",
  "choices": ["Uydu yayını", "Renkli televizyon", "Canlı radyo", "Uluslararası ortak yapım"],
  "answer": 1,
  "hint": "O zamana kadar dünya Dünya Kupası'nı siyah-beyaz ekranlarda izliyordu.",
  "fact": "1970 Meksika, Dünya Kupası'nın renkli TV ile buluştuğu ilk turnuvaydı. Brezilya'nın sarı forması, o yayınların simgesi haline geldi. Pelé'nin üçüncü şampiyonluğunu dünya, ilk kez gerçek renklerinde izledi.",
  "image": null,
  "tags": ["1970", "Meksika", "renkli TV", "teknoloji", "Pelé", "Brezilya"]
},
 {
  "difficulty": "easy",
  "points": 1,
  "text": "2026 FIFA Dünya Kupası'na kaç takım katılıyor?",
  "choices": ["32", "40", "48", "64"],
  "answer": 2,
  "hint": "Bu sayı, önceki yedi turnuvadan tam 16 fazla.",
  "fact": "48 takımlı format, 1998'den bu yana ilk büyük format değişikliği. Maç sayısı da 64'ten 104'e çıktı.",
  "image": null,
  "fact_image": null,
  "tags": ["wc-2026", "format", "kuzey-amerika", "web-kaynak"]
},
{
  "difficulty": "easy",
  "points": 1,
  "text": "2026 Dünya Kupası'nda takımlar kaç gruba ayrıldı?",
  "choices": ["8", "10", "12", "16"],
  "answer": 2,
  "hint": "Her grupta 4 takım var — toplam takım sayısını buradan geriye doğru hesapla.",
  "fact": "FIFA aslında önce 16 grup x 3 takımlı bir format düşünmüştü, ama maç fixing riski nedeniyle 12 grup x 4 takıma geçildi.",
  "image": null,
  "fact_image": null,
  "tags": ["wc-2026", "format", "web-kaynak"]
},
{
  "difficulty": "medium",
  "points": 2,
  "text": "2026 formatında grup aşamasından sonra ilk kez uygulanan yeni tur hangisi?",
  "choices": ["Çeyrek Final", "Yarı Final", "32'lik Tur", "16'lık Tur"],
  "answer": 2,
  "hint": "Bu tur, daha önce hiçbir erkekler Dünya Kupası'nda uygulanmamıştı ve 16'lık turun yerini aldı.",
  "fact": "32'lik tura, gruplardan çıkan ilk ikişer takım artı en iyi 8 üçüncü takım katılıyor. Şampiyon olmak için gereken maç sayısı da 7'den 8'e çıktı.",
  "image": null,
  "fact_image": null,
  "tags": ["wc-2026", "format", "web-kaynak"]
},
{
  "difficulty": "easy",
  "points": 1,
  "text": "2026 Dünya Kupası'na kaç ülke ortak ev sahipliği yapıyor?",
  "choices": ["1", "2", "3", "4"],
  "answer": 2,
  "hint": "Bu, tarihte ilk kez üç ülkenin birlikte ev sahipliği yaptığı bir Dünya Kupası.",
  "fact": "ABD, Meksika ve Kanada ortak ev sahibi. Meksika bu sayede aynı zamanda üç kez Dünya Kupası'na ev sahipliği yapan ilk ülke oldu (1970, 1986, 2026).",
  "image": null,
  "fact_image": null,
  "tags": ["wc-2026", "ev-sahipligi", "kuzey-amerika", "web-kaynak"]
},
{
  "difficulty": "medium",
  "points": 2,
  "text": "2026 Dünya Kupası finali hangi şehirde oynanıyor?",
  "choices": ["Los Angeles", "New York / New Jersey", "Dallas", "Miami"],
  "answer": 1,
  "hint": "Stadyum teknik olarak komşu eyalette ama Manhattan'a sadece 10 km mesafede.",
  "fact": "Final MetLife Stadium'da, 19 Temmuz'da oynanıyor. Stadyum New Jersey'de ama New York metropol bölgesi olarak pazarlanıyor.",
  "image": null,
  "fact_image": null,
  "tags": ["wc-2026", "final", "stadyum", "kuzey-amerika", "web-kaynak"]
},
{
  "difficulty": "medium",
  "points": 2,
  "text": "2026 Dünya Kupası'nın açılış maçı hangi iki takım arasında oynandı?",
  "choices": ["Meksika - ABD", "Meksika - Güney Afrika", "Kanada - Meksika", "ABD - Katar"],
  "answer": 1,
  "hint": "Bu eşleşme, 2010 Dünya Kupası'nın açılış maçının bir tekrarıydı — o maç 1-1 bitmişti.",
  "fact": "Maç 11 Haziran'da Mexico City Stadium'da (Estadio Azteca) oynandı.",
  "image": null,
  "fact_image": null,
  "tags": ["wc-2026", "tarih", "stadyum", "web-kaynak"]
},
{
  "difficulty": "hard",
  "points": 3,
  "text": "2026'da hangi stadyum, tarihte üç farklı Dünya Kupası'na ev sahipliği yapan ilk stadyum oldu?",
  "choices": ["Maracanã", "Estadio Azteca", "Rose Bowl", "Wembley"],
  "answer": 1,
  "hint": "Bu stadyumda hem Pelé hem de Maradona kupa kaldıran finallere sahne olmuştu.",
  "fact": "Estadio Azteca, 1970 ve 1986 finallerinin ardından 2026'da da (Mexico City Stadium adıyla) açılış maçını ağırladı. Deniz seviyesinden 2.200 metre yükseklikte.",
  "image": null,
  "fact_image": null,
  "tags": ["wc-2026", "stadyum", "rekor", "web-kaynak"]
},
{
  "difficulty": "medium",
  "points": 2,
  "text": "2026 Dünya Kupası'nın en büyük kapasiteli stadyumu hangi şehirde?",
  "choices": ["Dallas", "Atlanta", "Mexico City", "New York"],
  "answer": 0,
  "hint": "Bu şehrin stadyumu aynı zamanda bir NFL takımına da ev sahipliği yapıyor ve turnuvanın en çok maç oynanan sahalarından biri.",
  "fact": "AT&T Stadium yaklaşık 94.000 kapasiteyle turnuvanın en büyüğü; bir yarı final dahil 9 maça ev sahipliği yapıyor.",
  "image": null,
  "fact_image": null,
  "tags": ["wc-2026", "stadyum", "rekor", "web-kaynak"]
},
{
  "difficulty": "easy",
  "points": 1,
  "text": "Kanada'da Dünya Kupası maçlarına ev sahipliği yapan iki şehir hangileri?",
  "choices": ["Toronto - Montreal", "Vancouver - Calgary", "Toronto - Vancouver", "Ottawa - Toronto"],
  "answer": 2,
  "hint": "Biri ülkenin doğu, diğeri batı kıyısında — ikisi de bu turnuvada ilk kez Dünya Kupası maçı oynatıyor.",
  "fact": "Toronto BMO Field, Vancouver ise BC Place'de maçlara ev sahipliği yapıyor. BMO Field, turnuvanın en küçük kapasiteli stadyumu.",
  "image": null,
  "fact_image": null,
  "tags": ["wc-2026", "ev-sahipligi", "kuzey-amerika", "web-kaynak"]
},
{
  "difficulty": "easy",
  "points": 1,
  "text": "2026 Dünya Kupası'nın üç resmi maskotundan Kanada'yı temsil eden hangisi?",
  "choices": ["Zayu", "Clutch", "Maple", "Trionda"],
  "answer": 2,
  "hint": "Bu karakter bir kaleci ve adını ülkenin ulusal simgesi olan bir ağaç yaprağından alıyor.",
  "fact": "Maple bir geyik (moose), kırmızı renkte ve kaleci pozisyonunda tasarlandı. Zayu (Meksika) jaguar-forvet, Clutch (ABD) kel kartal-forvet.",
  "image": null,
  "fact_image": null,
  "tags": ["wc-2026", "maskot", "web-kaynak"]
},
{
  "difficulty": "easy",
  "points": 1,
  "text": "2026 Dünya Kupası'nın Adidas imzalı resmi maç topunun adı nedir?",
  "choices": ["Al Rihla", "Telstar", "Trionda", "Jabulani"],
  "answer": 2,
  "hint": "İsim İspanyolca'da 'üç dalga' anlamına geliyor — üç ev sahibi ülkeye bir gönderme.",
  "fact": "Top; kırmızı, yeşil ve mavi renklerle üç ev sahibi ülkeyi simgeliyor ve VAR için 500Hz hareket sensörü içeriyor.",
  "image": null,
  "fact_image": null,
  "tags": ["wc-2026", "top", "web-kaynak"]
},
{
  "difficulty": "medium",
  "points": 2,
  "text": "2026 Dünya Kupası şampiyonuna verilecek ödül parası ne kadar?",
  "choices": ["42 milyon $", "38 milyon $", "50 milyon $", "60 milyon $"],
  "answer": 2,
  "hint": "Bu miktar, Katar 2022'deki rakamdan 8 milyon dolar daha fazla.",
  "fact": "Ödül parası 1982'de 2,2 milyon dolardı — 2026'da 50 milyon dolara ulaştı.",
  "image": null,
  "fact_image": null,
  "tags": ["wc-2026", "rekor", "web-kaynak"]
},
{
  "difficulty": "easy",
  "points": 1,
  "text": "2026'ya kupayı savunan şampiyon olarak giren ülke hangisi?",
  "choices": ["Fransa", "Almanya", "Arjantin", "Brezilya"],
  "answer": 2,
  "hint": "Bu ülke, 2022 finalinde rakibini penaltılarla geçmişti — 3-3'lük bir uzatma sonrası.",
  "fact": "Arjantin, Scaloni yönetiminde Fransa'yı penaltılarla geçerek şampiyon olmuştu. Kupayı savunabilirse tarihte bunu başaran üçüncü ülke olacak.",
  "image": null,
  "fact_image": null,
  "tags": ["wc-2026", "tarih", "web-kaynak"]
},
{
  "difficulty": "medium",
  "points": 2,
  "text": "2026 Dünya Kupası'nda toplam kaç maç oynanıyor?",
  "choices": ["64", "80", "98", "104"],
  "answer": 3,
  "hint": "Bu sayı, 2022'dekinden tam 40 fazla.",
  "fact": "48 takım ve yeni 32'lik tur sayesinde maç sayısı 64'ten 104'e çıktı — turnuva da 39 gün sürüyor.",
  "image": null,
  "fact_image": null,
  "tags": ["wc-2026", "format", "rekor", "web-kaynak"]
},
{
  "difficulty": "hard",
  "points": 3,
  "text": "Aşağıdaki ülkelerden hangisi 2026 Dünya Kupası'na İLK KEZ katılmıyor?",
  "choices": ["Cabo Verde", "Curaçao", "Haiti", "Ürdün"],
  "answer": 2,
  "hint": "Bu ülke, listedeki diğer üçünün aksine bu sahneye tamamen yabancı değil — daha önce bir kez burada oynamış ama araya on yıllar süren uzun bir sessizlik girmişti.",
  "fact": "Haiti ilk kez 1974'te Batı Almanya'da sahne almıştı; 2026'da 52 yıl aradan sonra ikinci kez katılıyor. Cabo Verde, Curaçao ve Ürdün ise gerçek anlamda ilk kez Dünya Kupası'ndalar.",
  "image": null,
  "fact_image": null,
  "tags": ["wc-2026", "ilk-katilim", "web-kaynak"]
}
  
 
  
];
